apps/friends/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login$', views.login, name='do_the_login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^register$', views.register),
    url(r'^home$', views.home, name='home'),
    url(r'^home/(?P<user_id>\d+)$', views.show),
    url(r'^home/(?P<friend_id>\d+)/create$', views.add_friend, name='add_friend'),
    url(r'^home/(?P<friend_id>\d+)/destroy$', views.lose_friend, name='lose_friend')
]

exam/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.friends.urls', namespace='login'))

]

apps/friends/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
import re
import bcrypt
from django.db import models
import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')
NAME_REGEX = re.compile(r'^[A-Za-z]\w+$')

class UserManager(models.Manager):
    def validate_login(self, post_data):
        errors = []
        # check DB for post_data['email']
        if len(self.filter(email=post_data['email'])) > 0:
            # check this user's password
            user = self.filter(email=post_data['email'])[0]
            if not bcrypt.checkpw(post_data['password'].encode(), user.password.encode()):
                errors.append('email/password incorrect')
        else:
            errors.append('email/password incorrect')

        if errors:
            return errors
        return user

    # def books_reviewed(self):
    #     return self.model.reviews_left.all().values('book').distict()

    def validate_registration(self, post_data):
        errors = []
        # check length of name fields
        if len(post_data['name']) < 2 or len(post_data['alias']) < 2:
            errors.append("name fields must be at least 3 characters")
        # check length of name password
        if len(post_data['password']) < 8:
            errors.append("password must be at least 8 characters")
        # check name fields for letter characters
        if not re.match(NAME_REGEX, post_data['name']):
            errors.append('name fields must be letter characters only')
        # check emailness of email
        if not re.match(EMAIL_REGEX, post_data['email']):
            errors.append("invalid email")
        # check uniqueness of email
        if len(User.objects.filter(email=post_data['email'])) > 0:
            errors.append("email already in name used")
        # check password == password_confirm
        if post_data['password'] != post_data['password_confirm']:
            errors.append("passwords do not match")
        if re.search(r"[!@$&{1,5}]", post_data['password']) is None:
            errors.append("Password should contain one of !@$&")
        try:
            datetime.datetime.strptime(post_data['dob'], '%Y-%m-%d').date()
        except ValueError:
            errors.append("Please enter a valid birthday")
        if not errors:
            # make our new user
            # hash password
            hashed = bcrypt.hashpw((post_data['password'].encode()), bcrypt.gensalt(5))

            new_user = self.create(
                name=post_data['name'],
                alias=post_data['alias'],
                email=post_data['email'],
                dob=post_data['dob'],
                password=hashed
            )
            return new_user
        return errors


class User(models.Model):
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    dob = models.DateField()
    password = models.CharField(max_length=255)
    objects = UserManager()

    def __str__(self):
        return self.email


class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='Owner')

    @classmethod
    def add_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        print new_friend
        friend.users.add(new_friend)
        # Creates a symmetrical relationship
        friend, created = cls.objects.get_or_create(
            current_user=new_friend)
        friend.users.add(current_user)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)
        # Removes the symmetrical relationship
        friend, created = cls.objects.get_or_create(
            current_user=new_friend)
        friend.users.remove(current_user)

apps/friends/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from .models import User, Friend
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from django.contrib import messages


# Create your views here.
def index(request):
    return render(request, 'login/index.html')


def register(request):
    result = User.objects.validate_registration(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    # Creates a friend object on registration
    current_user = User.objects.get(id=request.session['user_id'])
    Friend.objects.create(current_user=current_user)
    messages.success(request, "Successfully registered!")
    return HttpResponseRedirect(reverse("login:home"))


def login(request):
    result = User.objects.validate_login(request.POST)
    if type(result) == list:
        for err in result:
            messages.error(request, err)
        return redirect('/')
    request.session['user_id'] = result.id
    messages.success(request, "Successfully logged in!")
    return HttpResponseRedirect(reverse("login:home"))


def logout(request):
    for key in request.session.keys():
        del request.session[key]
    return redirect('/')


def show(request, user_id):
    if 'user_id' not in request.session:
        return redirect('/')

    user = User.objects.get(id=user_id)
    context = {
       'user': user,
    }
    return render(request, 'login/show.html', context)


def home(request):
    if 'user_id' not in request.session:
        return redirect('/')
    else:
        current_user = User.objects.get(id=request.session['user_id'])
        others = User.objects.exclude(id=request.session['user_id'])
        friend = Friend.objects.get(current_user=current_user)
        friends = friend.users.all()
        context = {
            'user': current_user,
            'others': others,
            'friends': friends
        }
        return render(request, 'home/home.html', context)


def add_friend(request, friend_id):
    if 'user_id' not in request.session:
        return redirect('/')
    else:
        friend = User.objects.get(id=friend_id)
        current_user = User.objects.get(id=request.session['user_id'])
        Friend.add_friend(current_user, friend)
        return redirect('login:home')


def lose_friend(request, friend_id):
    if 'user_id' not in request.session:
        return redirect('/')
    else:
        friend = User.objects.get(id=friend_id)
        current_user = User.objects.get(id=request.session['user_id'])
        Friend.lose_friend(current_user, friend)
        return redirect('login:home')

apps/friends/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <link href="{% static 'home/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <h1> Welcome, {{ user.alias }}</h1>

        <a class="logout" href="{% url 'login:logout' %}">Logout</a>
    </header>

    <h1>Friends:</h1>
    <div class="container">
        {% if not friends %}
                <h3>You don't have friends yet.</h3>


         {% else %}
         <table class="table-striped table">
            <thead>
                  <tr>
                    <th>Alias</th>
                    <th>Actions</th>
                  </tr>
              </thead>
         {% endif %}
             {% for friend in friends %}
              <tbody>
                <td>{{ friend.alias }}</td>
                <td><a href="home/{{ friend.id }}/destroy"><button type="button" class="btn btn-warning btn-xs">Remove friend</button></a></td>
                <td><a href="home/{{ friend.id }}"><button type="button" class="btn btn-primary btn-xs">Show User</button></a></td>

             {%  endfor %}
              </tbody>
         </table>
    </div>
    <h1>Other Users:</h1>
    <div class="container">
         <table class="table-striped table">
              <thead>
                  <tr>
                    <th>Alias</th>
                    <th>Actions</th>
                  </tr>
              </thead>
              <tbody>
            {% for other in others %}
                 {% if not other in friends %}
                     <tr>
                         <td><a href="home/{{ other.id }}">{{ other.alias }}</a></td>
                         <td><a href="home/{{ other.id }}/create"><button type="button" class="btn btn-success btn-xs">Add friend</button></a></td>
                     </tr>

         {% endif %}
     {%  endfor %}
              </tbody>
          </table>
    </div>
</body>
</html>

apps/friends/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% load staticfiles %}
        <link href="{% static 'login/style.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if messages %}
        <div class="messages">
            {% for message in messages %}
            <p class="{{ message.tags }}">{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <h1>Welcome Guest!</h1>
        <div class="registration">
            <h2>Registration</h2>
            <form action="/register" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name">
                </div>
                <div class="form-group">
                    <label for="alias">Alias</label>
                    <input type="text" name="alias">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email">
                </div>
                <div class="form-group">
                    <label for="dob">Birthdate:</label>
                    <input type='date'  name='dob'>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password">
                </div>
                <div class="form-group">
                    <label for="password_confirm">Confirm Password</label>
                    <input type="password" name="password_confirm">
                </div>
                <input type="submit" class="btn btn-primary" value='Register'>
            </form>
        </div>
        <div class="login">
            <h2>Login</h2>
            <form action="{% url 'login:do_the_login' %}" method="POST">
                {% csrf_token %}
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password">
            </div>
            <input class="btn btn-primary" type="submit" value='Login'>
        </form>
        </div>
    </body>
</html>

apps/friends/templates/login/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% load staticfiles %}
        <link href="{% static 'login/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="Nav">
            <a href="/home">Home</a> <a href="{% url 'login:logout' %}">Logout</a>
        </div>
        <div class="content">
            <h1>{{ user.name }}'s profile</h1>
            <h3><strong>User Alias: </strong>{{user.alias}}</h3>
            <h3><strong>Name: </strong> {{user.name}}</h3>
            <h3><strong>Email: </strong> {{user.email}}</h3>
        </div>

    </body>
</html>